# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  MonoVulkan_config = debug

else ifeq ($(config),release)
  MonoVulkan_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := MonoVulkan

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

MonoVulkan:
ifneq (,$(MonoVulkan_config))
	@echo "==== Building MonoVulkan ($(MonoVulkan_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(MonoVulkan_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   MonoVulkan"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"